### ISSUE TITLE
Tab separated input files

### ISSUE THREAD

**Issue by panpan2** [souffle-lang/souffle-lang.github.io#20]
I was following the ["A simple example"](https://souffle-lang.github.io/docs/simple/) article from the docs website (file: [simple.md](https://github.com/souffle-lang/souffle-lang.github.io/blob/c45d9a77302ba28408b9b1dfb55832992eba9a44/_docs/simple.md)) and spend some time figuring out why the example wasn't working locally for me. The reason was that I was using spaces in the input file (I even copied the example by my editor overrides tabs :) ). I was wondering whether adding in the article the detail that the input file should be "tab-separated" would be useful to other new people reading the docs.

Edit:
With "wasn't working" I mean I was getting an error "Error loading data: Values missing in line 1; cannot parse fact file edge.facts!" which at that point didn't make sense to me, but now it does because I know that the parser probably looks for a tab separator.

**Comment by b-scholz** [comment]
Thanks for this feedback. We will work on it!

**Comment by mmcgr** [comment]
I updated the sample to use tabs, and mentioned that it was tab-separated in the description.
