### ISSUE TITLE
Does not interpret hexadecimal numbers correctly from input files

### ISSUE THREAD

**Issue by shrutihiray** [souffle-lang/souffle-lang.github.io#35]
When using .input directive to input data from files with hexadecimal numbers, its interpreted incorrectly. For eg. 0x34 is interpreted as 0. 
Please do the required changes.
Thanks!

**Comment by mmcgr** [comment]
I've added this as an issue to the repo for souffle code - https://github.com/souffle-lang/souffle/issues/1174
