### ISSUE TITLE
Invalid TLS certificate for souffle-lang.org

### ISSUE THREAD

**Issue by lexibrent** [souffle-lang/souffle-lang.github.io#5]
Visiting https://souffle-lang.org/  results in a certificate error. It appears that the certificate being used is for `*.github.com`, and does not include `souffle-lang.org` in the CN or SAN fields.

This is especially bad because [Google has indexed the Souffle documentation](https://www.google.com.au/search?q=site%3Asouffle-lang.org) using HTTPS URIs, so clicking on documentation links from Google search results leads to an error message like the one shown below:

![image](https://user-images.githubusercontent.com/1594962/35784484-f128654e-0a6b-11e8-801b-99be86649e13.png)

**Comment by lexibrent** [comment]
Looking online, it seems that GitHub might only support TLS for `*.github.io` domains at the moment. CloudFlare's free SSL service appears to be the most common workaround for getting TLS working properly with custom domains hosted on GH Pages.

**Comment by b-scholz** [comment]
How does this work?

**Comment by lexibrent** [comment]
The way CloudFlare works is:
1. You point your domain name to their name servers and set up DNS records with CloudFlare as needed.
2. When someone visits your site, the request goes via CloudFlare's servers before going to github.io. 

With the "Basic SSL" option, CloudFlare will automatically issue a free SSL certificate for your domain and use it on their edge servers when serving web requests. So it looks like this:

Web User <--> CloudFlare <--> GitHub.io

The first hop is encrypted using a free certificate that CloudFlare issues, so it appears as a valid HTTPS session when users connect to the site. The second hop between CF and GH is unencrypted. This shouldn't matter here, since the Souffle site is completely static anyway and there's no sensitive data being transmitted.

Main advantages of setting up TLS via CloudFlare are:
- You get to keep using GitHub pages for free, and CloudFlare is also free
- No need to buy external hosting and pay for and manage your own TLS certificate.
- The Souffle website links from Google won't show TLS errors
- Google will rank the Souffle website higher, because their algorithm takes TLS into account
- Later this year, Chrome will become the first browser to start showing HTTP connections with a red "insecure" warning in the address bar. If you enable TLS via CloudFlare, the Souffle site will show up as "secure" in Chrome.

**Comment by b-scholz** [comment]
We solved the issue - the problem was that the apex domain was muddled with the www subdomain. Also, we needed a redirect from the apex domain to the www subdomain. The redirect had to be done by the DNS provider.
