### ISSUE TITLE
functor problem

### ISSUE THREAD

**Issue by lyj18688610256** [souffle-lang/souffle-lang.github.io#96]
// introduce new functor f: number -> number
.functor f(x:number):number

.decl A(x:number) 
.output A
A(1). 
A(@f(i)) :- A(i), @f(i) < 100.

when I run the code above ,it occurs such error below
![image](https://user-images.githubusercontent.com/60656299/132146360-c7ce04c6-67c4-44ee-a456-a3c2e92c4d3e.png)

**Comment by b-scholz** [comment]
Which version of soufflé do you use - it seems to be an old one?

**Comment by lyj18688610256** [comment]
version 2.0.2

**Comment by b-scholz** [comment]
You need to upgrade to the latest release.

**Comment by lyj18688610256** [comment]
OK,thanks a lot

**Comment by lyj18688610256** [comment]
@b-scholz ,I test it in souffle 2.1,it occurs such below error
![image](https://user-images.githubusercontent.com/60656299/132283596-4b0d0b36-58fd-44eb-a1ce-8a4835e147d8.png)

**Comment by b-scholz** [comment]
You cannot load the dynamic library. Please follow the instructions for loading it.

**Comment by lyj18688610256** [comment]
I'm sorry,I am not familiar with souffle,how to load?can you give me instructions?

**Comment by b-scholz** [comment]
Do you have a MAC or UNIX?

**Comment by lyj18688610256** [comment]
Yes.I hava unix

**Comment by b-scholz** [comment]
Can you follow the instructions:
https://souffle-lang.github.io/functors

You need to build your user-defined functor in the form of a C++ program and compile it adequately. Special care must be taken if you have chosen 64bit for RAM_DOMAIN_SIZE. 

You can compile the C++ as follows:

```
g++ functors.cpp -c -fPIC -o functors.o 
g++ -shared -o libfunctors.so functors.o 
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}`pwd`
```

and the interpreter and compiler of Souffle should pick the library up. 

Note you can compile the program using the `-o <exe>` option.

**Comment by lyj18688610256** [comment]
OK,thank you,I will have a try
